
export enum AssetType {
  CASH = 'CASH',
  STOCK = 'STOCK',
  CRYPTO = 'CRYPTO'
}

export interface Asset {
  id: string;
  name: string;
  ticker?: string; // e.g., AAPL, BTC
  type: AssetType;
  quantity: number;
  currentPrice: number; // Unit price
  currency: string;
  lastUpdated?: string;
}

export enum OptionType {
  SHORT_PUT = 'SHORT_PUT',
  COVERED_CALL = 'COVERED_CALL'
}

export interface OptionTrade {
  id: string;
  ticker: string;
  type: OptionType;
  openDate: string;
  expiryDate: string;
  strikePrice: number;
  premium: number; // Total premium received or paid
  collateralOrCost: number; // Margin for Short Put, Cost for Long Call
  status: 'OPEN' | 'CLOSED' | 'EXPIRED';
  closePrice?: number; // Price when closed
  notes?: string;
}

// Page 3: Monthly P&L
export interface PnLEntry {
  id: string;
  date: string;
  description: string;
  amount: number; // Positive for Profit, Negative for Loss
  type: 'OPTION' | 'STOCK' | 'CRYPTO' | 'DIVIDEND' | 'OTHER';
  isAutoGenerated?: boolean; // If true, derived from OptionTrade
}

// Page 4: Airdrop
export type AirdropStatus = 'New' | 'Farming' | 'Waitlist' | 'Claimable' | 'Finished';

export interface AirdropProject {
  id: string;
  name: string;
  twitterUrl?: string;
  status: AirdropStatus;
  notes?: string;
  priority?: 'High' | 'Medium' | 'Low';
}

// Cloud Sync Configuration
export interface SyncConfig {
  githubToken: string;
  gistId: string;
  lastSyncTime?: string;
}
