
import React, { useMemo, useState } from 'react';
import { OptionTrade, OptionType, PnLEntry } from '../types';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, ReferenceLine, Cell } from 'recharts';
import { Plus, Trash2, TrendingUp, TrendingDown, DollarSign, Calendar } from 'lucide-react';

interface MonthlyPnLProps {
  trades: OptionTrade[];
  manualEntries: PnLEntry[];
  setManualEntries: React.Dispatch<React.SetStateAction<PnLEntry[]>>;
}

const MonthlyPnL: React.FC<MonthlyPnLProps> = ({ trades, manualEntries, setManualEntries }) => {
  const [selectedMonth, setSelectedMonth] = useState<string>(new Date().toISOString().slice(0, 7)); // YYYY-MM
  
  // Manual Entry Form State
  const [newEntry, setNewEntry] = useState<Partial<PnLEntry>>({
    date: new Date().toISOString().slice(0, 10),
    type: 'STOCK',
    amount: 0,
    description: ''
  });

  // 1. Generate P&L from Options
  const optionEntries: PnLEntry[] = useMemo(() => {
    const entries: PnLEntry[] = [];
    
    trades.forEach(trade => {
      // Event 1: Open Trade
      // Short Put: Receive Premium (Income +)
      // Long Call: Pay Premium (Cost -) (Wait, usually premium is cost basis. Let's treat it as Cashflow)
      // NOTE: For P&L, usually we track "Realized".
      // Cash Flow approach:
      // Short Put Open: +Premium
      // Long Call Open: -Premium (Cost)
      
      const openAmount = trade.type === OptionType.SHORT_PUT ? trade.premium : -trade.premium;
      entries.push({
        id: `opt-open-${trade.id}`,
        date: trade.openDate,
        description: `Open ${trade.type} ${trade.ticker} @${trade.strikePrice}`,
        amount: openAmount,
        type: 'OPTION',
        isAutoGenerated: true
      });

      // Event 2: Close Trade (if closed)
      if (trade.status === 'CLOSED' && trade.closePrice !== undefined && trade.expiryDate) {
        // Short Put Close: Buy back (-Cost)
        // Long Call Close: Sell (+Income)
        const closeAmount = trade.type === OptionType.SHORT_PUT ? -trade.closePrice : trade.closePrice;
         entries.push({
          id: `opt-close-${trade.id}`,
          date: trade.expiryDate, // Using expiry date as close date proxy if not available
          description: `Close ${trade.type} ${trade.ticker}`,
          amount: closeAmount,
          type: 'OPTION',
          isAutoGenerated: true
        });
      }
    });
    return entries;
  }, [trades]);

  // 2. Combine all entries
  const allEntries = useMemo(() => {
    return [...optionEntries, ...manualEntries].sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
  }, [optionEntries, manualEntries]);

  // 3. Aggregate by Month for Chart
  const monthlyData = useMemo(() => {
    const map = new Map<string, number>();
    
    // Initialize last 6 months
    for (let i = 5; i >= 0; i--) {
        const d = new Date();
        d.setMonth(d.getMonth() - i);
        const key = d.toISOString().slice(0, 7);
        map.set(key, 0);
    }

    allEntries.forEach(e => {
      const month = e.date.slice(0, 7);
      const current = map.get(month) || 0;
      map.set(month, current + e.amount);
    });

    return Array.from(map.entries())
        .sort((a, b) => a[0].localeCompare(b[0]))
        .map(([name, value]) => ({ name, value }));
  }, [allEntries]);

  // 4. Current Month Stats
  const currentMonthEntries = allEntries.filter(e => e.date.startsWith(selectedMonth));
  const totalGain = currentMonthEntries.filter(e => e.amount > 0).reduce((sum, e) => sum + e.amount, 0);
  const totalLoss = currentMonthEntries.filter(e => e.amount < 0).reduce((sum, e) => sum + e.amount, 0);
  const netPnL = totalGain + totalLoss;

  const handleAddEntry = () => {
    if (!newEntry.amount || !newEntry.description) return;
    const entry: PnLEntry = {
        id: Date.now().toString(),
        date: newEntry.date!,
        description: newEntry.description!,
        amount: Number(newEntry.amount),
        type: newEntry.type as any,
        isAutoGenerated: false
    };
    setManualEntries([entry, ...manualEntries]);
    setNewEntry({ ...newEntry, amount: 0, description: '' });
  };

  const handleDeleteEntry = (id: string) => {
      if(confirm("Delete this entry?")) {
          setManualEntries(manualEntries.filter(e => e.id !== id));
      }
  };

  return (
    <div className="space-y-6">
       {/* Chart Section */}
       <div className="bg-slate-900 border border-slate-800 p-6 rounded-2xl shadow-lg">
          <h2 className="text-xl font-bold text-white mb-6 flex items-center">
              <TrendingUp className="mr-2 text-blue-500"/> 每月損益趨勢 (Monthly P&L)
          </h2>
          <div className="h-72 w-full">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={monthlyData} margin={{ top: 5, right: 30, left: 20, bottom: 5 }}>
                <CartesianGrid strokeDasharray="3 3" stroke="#334155" vertical={false} />
                <XAxis dataKey="name" stroke="#94a3b8" tick={{fontSize: 12}} />
                <YAxis stroke="#94a3b8" tickFormatter={(val) => `$${val}`} />
                <Tooltip 
                    contentStyle={{ backgroundColor: '#1e293b', borderColor: '#334155', color: '#fff' }}
                    cursor={{fill: 'rgba(255,255,255,0.05)'}}
                    formatter={(value: number) => [`$${value.toLocaleString()}`, 'Net P&L']}
                />
                <ReferenceLine y={0} stroke="#64748b" />
                <Bar dataKey="value" radius={[4, 4, 0, 0]}>
                  {monthlyData.map((entry, index) => (
                    <Cell key={`cell-${index}`} fill={entry.value >= 0 ? '#10b981' : '#ef4444'} />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </div>
       </div>

       {/* Detailed Month View */}
       <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Summary Cards */}
          <div className="lg:col-span-1 space-y-4">
              <div className="bg-slate-900 border border-slate-800 p-6 rounded-2xl">
                  <label className="text-gray-400 text-sm mb-2 block">選擇月份</label>
                  <input 
                    type="month" 
                    value={selectedMonth}
                    onChange={(e) => setSelectedMonth(e.target.value)}
                    className="w-full bg-slate-950 border border-slate-700 text-white rounded-lg p-2.5 focus:border-blue-500 outline-none mb-6"
                  />
                  
                  <div className="space-y-4">
                      <div className="flex justify-between items-center p-3 bg-green-900/20 rounded-lg border border-green-900/30">
                          <span className="text-green-400 text-sm">總收益 (Gains)</span>
                          <span className="text-xl font-bold text-green-400">+${totalGain.toLocaleString()}</span>
                      </div>
                      <div className="flex justify-between items-center p-3 bg-red-900/20 rounded-lg border border-red-900/30">
                          <span className="text-red-400 text-sm">總虧損 (Losses)</span>
                          <span className="text-xl font-bold text-red-400">${totalLoss.toLocaleString()}</span>
                      </div>
                      <div className="pt-4 border-t border-slate-800">
                          <div className="flex justify-between items-center">
                              <span className="text-gray-300 font-medium">淨損益 (Net)</span>
                              <span className={`text-2xl font-bold ${netPnL >= 0 ? 'text-blue-400' : 'text-orange-400'}`}>
                                  {netPnL >= 0 ? '+' : ''}{netPnL.toLocaleString()}
                              </span>
                          </div>
                      </div>
                  </div>
              </div>

              {/* Add Manual Entry */}
              <div className="bg-slate-900 border border-slate-800 p-6 rounded-2xl">
                  <h3 className="text-white font-semibold mb-4 flex items-center">
                      <Plus className="w-4 h-4 mr-2" /> 新增損益記錄
                  </h3>
                  <div className="space-y-3">
                      <input 
                        type="date" 
                        className="w-full bg-slate-950 border border-slate-700 rounded-lg p-2 text-white text-sm"
                        value={newEntry.date}
                        onChange={(e) => setNewEntry({...newEntry, date: e.target.value})}
                      />
                      <select
                        className="w-full bg-slate-950 border border-slate-700 rounded-lg p-2 text-white text-sm"
                        value={newEntry.type}
                        onChange={(e) => setNewEntry({...newEntry, type: e.target.value as any})}
                      >
                          <option value="STOCK">股票 (Stock)</option>
                          <option value="CRYPTO">加密貨幣 (Crypto)</option>
                          <option value="DIVIDEND">股息 (Dividend)</option>
                          <option value="OTHER">其他 (Other)</option>
                      </select>
                      <input 
                        type="text" 
                        placeholder="描述 (e.g. Sold NVDA)" 
                        className="w-full bg-slate-950 border border-slate-700 rounded-lg p-2 text-white text-sm"
                        value={newEntry.description}
                        onChange={(e) => setNewEntry({...newEntry, description: e.target.value})}
                      />
                      <input 
                        type="number" 
                        placeholder="金額 (+賺 / -蝕)" 
                        className="w-full bg-slate-950 border border-slate-700 rounded-lg p-2 text-white text-sm"
                        value={newEntry.amount || ''}
                        onChange={(e) => setNewEntry({...newEntry, amount: parseFloat(e.target.value)})}
                      />
                      <button 
                        onClick={handleAddEntry}
                        className="w-full bg-blue-600 hover:bg-blue-500 text-white py-2 rounded-lg text-sm font-medium transition"
                      >
                          確認添加
                      </button>
                  </div>
              </div>
          </div>

          {/* Transactions List */}
          <div className="lg:col-span-2 bg-slate-900 border border-slate-800 rounded-2xl shadow-lg overflow-hidden flex flex-col">
              <div className="p-6 border-b border-slate-800">
                  <h3 className="text-lg font-semibold text-white">本月明細 ({selectedMonth})</h3>
              </div>
              <div className="flex-1 overflow-auto">
                  <table className="w-full text-left">
                      <thead className="bg-slate-950 text-gray-400 text-xs uppercase sticky top-0">
                          <tr>
                              <th className="px-6 py-4">日期</th>
                              <th className="px-6 py-4">類型</th>
                              <th className="px-6 py-4">項目</th>
                              <th className="px-6 py-4 text-right">金額</th>
                              <th className="px-6 py-4 text-center">操作</th>
                          </tr>
                      </thead>
                      <tbody className="divide-y divide-slate-800">
                          {currentMonthEntries.map(entry => (
                              <tr key={entry.id} className="hover:bg-slate-800/50 transition">
                                  <td className="px-6 py-4 text-gray-400 text-sm font-mono">{entry.date}</td>
                                  <td className="px-6 py-4">
                                      <span className={`text-xs font-bold px-2 py-1 rounded ${
                                          entry.type === 'OPTION' ? 'bg-purple-900/30 text-purple-400' :
                                          entry.type === 'DIVIDEND' ? 'bg-yellow-900/30 text-yellow-400' :
                                          'bg-blue-900/30 text-blue-400'
                                      }`}>
                                          {entry.type}
                                      </span>
                                  </td>
                                  <td className="px-6 py-4 text-white text-sm">
                                      {entry.description}
                                      {entry.isAutoGenerated && <span className="ml-2 text-xs text-gray-500">(Auto)</span>}
                                  </td>
                                  <td className={`px-6 py-4 text-right font-mono font-medium ${entry.amount >= 0 ? 'text-green-400' : 'text-red-400'}`}>
                                      {entry.amount >= 0 ? '+' : ''}{entry.amount.toLocaleString()}
                                  </td>
                                  <td className="px-6 py-4 text-center">
                                      {!entry.isAutoGenerated && (
                                          <button 
                                            onClick={() => handleDeleteEntry(entry.id)}
                                            className="text-gray-600 hover:text-red-500 transition"
                                          >
                                              <Trash2 size={16} />
                                          </button>
                                      )}
                                  </td>
                              </tr>
                          ))}
                          {currentMonthEntries.length === 0 && (
                              <tr>
                                  <td colSpan={5} className="p-8 text-center text-gray-500">
                                      本月暫無記錄
                                  </td>
                              </tr>
                          )}
                      </tbody>
                  </table>
              </div>
          </div>
       </div>
    </div>
  );
};

export default MonthlyPnL;
